## Multi Layer Perceptron ( MLP )  __________________________________

Importar as bibliotecas

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
import tensorflow as tf
from keras import utils

### Carregar Base de Dados

In [ ]:
data=pd.read_csv("../../data/databaseIris.csv")
data.sample(10)

,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
66,5.6,3.0,4.5,1.5,Iris-versicolor
29,4.7,3.2,1.6,0.2,Iris-setosa
72,6.3,2.5,4.9,1.5,Iris-versicolor
2,4.7,3.2,1.3,0.2,Iris-setosa
43,5.0,3.5,1.6,0.6,Iris-setosa
105,7.6,3.0,6.6,2.1,Iris-virginica
81,5.5,2.4,3.7,1.0,Iris-versicolor
122,7.7,2.8,6.7,2.0,Iris-virginica
7,5.0,3.4,1.5,0.2,Iris-setosa
45,4.8,3.0,1.4,0.3,Iris-setosa


###  Codificar as categorias

In [ ]:
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2

data=data.iloc[np.random.permutation(len(data))]
print(data.sample(10))


     SepalLength  SepalWidth  PetalLength  PetalWidth Species
29           4.7         3.2          1.6         0.2       0
113          5.7         2.5          5.0         2.0       2
138          6.0         3.0          4.8         1.8       2
80           5.5         2.4          3.8         1.1       1
70           5.9         3.2          4.8         1.8       1
59           5.2         2.7          3.9         1.4       1
69           5.6         2.5          3.9         1.1       1
64           5.6         2.9          3.6         1.3       1
93           5.0         2.3          3.3         1.0       1
41           4.5         2.3          1.3         0.3       0


### Separar dados descritivos das classes

In [ ]:
X=data.iloc[:,:4].values
y=data.iloc[:,4].values

In [ ]:
print("Shape of X",X.shape)
print("Shape of y",y.shape)

Shape of X (150, 4)
Shape of y (150,)


### Dividir dados para treinamento, validação e teste

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import numpy as np

#Normalizar os dados
X_normalized = normalize(X,axis=0)

X_train_val,X_test,y_train_val,y_test=train_test_split(X_normalized,y,test_size=0.1,random_state=42)
X_train,X_val,y_train,y_val=train_test_split(X_train_val,y_train_val,test_size=0.1,random_state=42)

#Transformar os rótulos em categorias
num_classes=3
y_train=utils.to_categorical(y_train,num_classes)
y_val=utils.to_categorical(y_val,num_classes)
y_test=utils.to_categorical(y_test,num_classes)



## Arquitetura do MLP

In [ ]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(16,input_dim=4,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))

model.add(tf.keras.layers.Dense(3,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,523 (21.57 KB)

 Trainable params: 5,523 (21.57 KB)

 Non-trainable params: 0 (0.00 B)

### Treinar a rede

In [ ]:
class_weights = {
    0:1.0, #peso da classe 0
    1:1.0, #peso da classe 1
    2:1.0, #peso da classe 2
}

In [ ]:
model.fit(X_train,y_train,validation_split=0.2,batch_size=16,epochs=50,verbose=1,class_weight=class_weights)


Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.5902 - loss: 1.0951 - val_accuracy: 0.5200 - val_loss: 1.0929
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6421 - loss: 1.0842 - val_accuracy: 0.4800 - val_loss: 1.0885
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5749 - loss: 1.0755 - val_accuracy: 0.5200 - val_loss: 1.0863
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5996 - loss: 1.0734 - val_accuracy: 0.5200 - val_loss: 1.0780
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6817 - loss: 1.0560 - val_accuracy: 0.5200 - val_loss: 1.0715
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7360 - loss: 1.0432 - val_accuracy: 0.5200 - val_loss: 1.0639
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6772 - loss: 1.0392 - val_accuracy: 0.5200 - val_loss: 1.0519
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7034 - loss: 1.0114 - val_accuracy: 0.5200 - val_loss: 1.0375


### Testar

In [ ]:
#Fazer previsoes nos dados de teste
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred,axis=1)

#Calcular a matriz de confusão
matriz_confusao=confusion_matrix(np.argmax(y_test,axis=1),y_pred_classes)

#Calcular a acurácia
acuracia=accuracy_score(np.argmax(y_test,axis=1),y_pred_classes)

#Calcular o score F1
f1=f1_score(np.argmax(y_test,axis=1),y_pred_classes,average='macro')

print("Matriz de confusão")
print(matriz_confusao)
print("Acuracia:")
print(acuracia)
print("Score F1")
print(f1)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Matriz de confusão
[[5 0 0]
 [0 7 1]
 [0 0 2]]
Acuracia:
0.9333333333333333
Score F1
0.9111111111111111


In [ ]:
model.layers[0].get_weights()[1]

array([ 0.02995397,  0.        ,  0.        ,  0.0130249 ,  0.        ,
        0.14803235,  0.        , -0.00047829,  0.11024   ,  0.        ,
        0.00806536,  0.03042303, -0.02368089,  0.06362233,  0.        ,
        0.10174508], dtype=float32)